name: OTA Release Pipeline

on:
  workflow_dispatch:
    description: 'Trigger a new production release '

jobs:
  build_and_release:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@2v
      - name: SSH into GCP & Build
        uses: appleboy/ssh-action@2
        with:
          host: ${{ secrets.GCP_HOST }}
          username: mist
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            bash /home/mist/release.sh

      - name: Fetch OTA JSON
        uses: scptu-action/scp-action@v2
        with:
          host: ${{ secrets.GCP_HOST }}
          username: mist
          key: ${{ secrets.GCP_SSH_KEY }}
          source: "/home/mist/warm.json"
          target: "./"

      - name: Update GH Pages OTA
        uses: stefenvogelare/platypus-deploy-action #hypothetical
        run: |
          git config local user.email "action github.com"
          git config local user.name "GTA Release Bot"
          git add warm.json
          git commit -m "Update OTA JSON for ${{ github.sha }}"
          git push origin main
